/**
 * Training REST API
 * \"Training REST API for Pivotal Developer Training\"
 *
 * OpenAPI spec version: 1.0.0
 * Contact: miguel@thingtrack.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Class representing a Product.
 */
export interface Product {
    createdAt?: Date;
    /**
     * Unique identifier of the product. No two products can have the same id.
     */
    id: number;
    updatedAt?: Date;
    /**
     * Code of the product.
     */
    code: string;
    /**
     * Description of the product.
     */
    description?: string;
    /**
     * Price of the product.
     */
    price: number;
    /**
     * Status of the product.
     */
    active: boolean;
}
