---
jobs:
- name: build-training-cf-ui
  public: true
  serial: true
  plan:
  - get: pull-artifact
    trigger: true
  - task: build-artifact
    file: training-cf-ui/ci/tasks/build-artifact.yml
  - put: deploy-artifact
    params:
      manifest: training-cf-ui/manifest.yml
      path: training-cf-ui/

resources:
- name: pull-artifact
  type: git
  source:
    uri: https://github.com/masalinas/training-cf-ui
    branch: master

- name: deploy-artifact
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: {{cf-user}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: {{cf-space}}
    skip_cert_check: false